"""nueva tabla negocios

Revision ID: 6327e31dda9b
Revises: c61ed4c48f7b
Create Date: 2026-05-17 00:27:32.460492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6327e31dda9b'
down_revision: Union[str, Sequence[str], None] = 'c61ed4c48f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negocios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negocios_id'), 'negocios', ['id'], unique=False)
    op.create_index(op.f('ix_negocios_name'), 'negocios', ['name'], unique=False)
    op.add_column('appointments', sa.Column('negocio_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'negocios', ['negocio_id'], ['id'])
    op.add_column('users', sa.Column('negocio_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'negocios', ['negocio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'negocio_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'negocio_id')
    op.drop_index(op.f('ix_negocios_name'), table_name='negocios')
    op.drop_index(op.f('ix_negocios_id'), table_name='negocios')
    op.drop_table('negocios')
    # ### end Alembic commands ###
