"""se agrego la tabla de barbers

Revision ID: 9a1a3a76beb5
Revises: 6327e31dda9b
Create Date: 2026-05-17 01:37:14.284324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1a3a76beb5'
down_revision: Union[str, Sequence[str], None] = '6327e31dda9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barbers_email'), 'barbers', ['email'], unique=True)
    op.create_index(op.f('ix_barbers_id'), 'barbers', ['id'], unique=False)
    op.create_index(op.f('ix_barbers_name'), 'barbers', ['name'], unique=False)
    op.drop_constraint(op.f('appointments_barber_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'barbers', ['barber_id'], ['id'])
    op.alter_column('negocios', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('negocios', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_barber_id_fkey'), 'appointments', 'users', ['barber_id'], ['id'])
    op.drop_index(op.f('ix_barbers_name'), table_name='barbers')
    op.drop_index(op.f('ix_barbers_id'), table_name='barbers')
    op.drop_index(op.f('ix_barbers_email'), table_name='barbers')
    op.drop_table('barbers')
    # ### end Alembic commands ###
