"""agregado del campo rol en la tabla barbers

Revision ID: afece5e4b38c
Revises: 9a1a3a76beb5
Create Date: 2026-05-18 06:42:27.730750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afece5e4b38c'
down_revision: Union[str, Sequence[str], None] = '9a1a3a76beb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('role', sa.String(length=20), nullable=False, server_default="barbero"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barbers', 'role')
    # ### end Alembic commands ###
